name: sistema_almox
description: Aplicativo de controle de almoxarifado
publish_to: 'none'

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  http: ^1.2.2
  supabase_flutter: ^2.10.1
  flutter_dotenv: ^6.0.0
  postgrest: ^2.5.0
  provider: ^6.1.5
  flutter_secure_storage: ^9.2.2
  mobile_scanner: ^5.1.1
  cached_network_image: ^3.3.1
  file_picker: ^8.0.0+1
  csv: ^6.0.0
  syncfusion_flutter_pdf: ^31.2.2
  path_provider: ^2.1.3
  open_file: ^3.3.2
  open_filex: ^4.5.0
  pdf: ^3.10.8
  file_saver: ^0.2.12
  printing: ^5.14.2
  share_plus: ^10.0.0
  qr_flutter: ^4.1.0
  image_picker: ^1.2.0
  image_cropper: ^11.0.0
  mask_text_input_formatter: ^2.9.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/navbar/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app-icon-solid.png"

  adaptive_icon_background: "#1D234F" 
  adaptive_icon_foreground: "assets/app-icon-transparent.png"

flutter_native_splash:
  color: "#1D234F"
  image: "assets/app-icon-transparent.png"

  android: true
  ios: true

  android_12:
    color: "#1D234F"
    image: "assets/app-icon-transparent.png"