name: sistema_almox
description: "Sistema de Estoque Militar"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1 
  shimmer: ^3.0.0
  http: ^1.2.2
  intl: ^0.19.0
  supabase_flutter: ^2.10.1
  flutter_dotenv: ^6.0.0
  provider: ^6.1.5+1
  mobile_scanner: ^5.1.1
  flutter_secure_storage: ^9.2.2
  flutter_native_splash: ^2.4.0
  cached_network_image: ^3.3.1
  file_picker: ^8.0.0+1
  csv: ^6.0.0 


dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lint: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/navbar/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app-icon-solid.png"

  adaptive_icon_background: "#1D234F" 
  adaptive_icon_foreground: "assets/app-icon-transparent.png"

flutter_native_splash:
  color: "#1D234F"
  image: "assets/app-icon-transparent.png"

  android: true
  ios: true

  android_12:
    color: "#1D234F"
    image: "assets/app-icon-transparent.png"