name: sistema_almox
description: "Sistema de Estoque Militar"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lint: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/navbar/
